adapter: lora
attn_implementation: eager
base_model: /home/seana/axolotl_project/models/phi-2/phi2
flash_attention: false
bf16: false
bnb_8bit_compute_dtype: float16
cutoff_len: 256
datasets:
  - path: /home/seana/axolotl_project/data/cot_10x10_1601to1750_99.jsonl
    type: alpaca

fp16: false
gradient_accumulation_steps: 8
group_by_length: false
learning_rate: 2e-4
llm_int8_enable_fp32_cpu_offload: true
load_in_4bit: false
load_in_8bit: true
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.05
lora_r: 8
lora_target_modules:
  - qkv_proj
  - out_proj
  - dense
  - dense_h_to_4h
  - dense_4h_to_h
lr_scheduler_type: cosine
micro_batch_size: 1
model_type: AutoModelForCausalLM
num_epochs: 3
num_train_epochs: 5
optimizer: adamw_torch
output_dir: /home/seana/axolotl_project/outputs/phi2-CoT-finetune2
peft_type: LORA
report_to: none
save_steps: 50
save_strategy: steps
save_total_limit: 2
seed: 42
special_tokens:
  pad_token: <|endoftext|>
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
use_bnb: true
val_set_size: 0.0
overwrite_prepared_dataset: true
warmup_ratio: 0.05
weight_decay: 0.01
resume_from_checkpoint: /home/seana/axolotl_project/outputs/phi2-CoT-finetune2/checkpoint-75
